name: Analyze with SonarCloud
on:
  push:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: SonarCloud Scan
        run: chmod +x ./gradlew && ./gradlew build sonar
        env:
          SONAR_SECRET: ${{ secrets.SONAR_TOKEN }}